### ISSUE TITLE
Please clarify me

### ISSUE THREAD

**Issue by BigGitWorld** [dadoonet/legacy-search#132]
Hello.
**I know this is not an issue. but I think there are a lot people who are confused like me.**

I'm really confused what is the best way of using the Elasticsearch in a spring boot project?
In fact, I have a spring boot project that is working now with spring data JPA and MySQL. 

Now, I need to store a lot data (thousands per second).
I read the MySQL and relational DB are not good (vertical scaling). So I want to store my data by the Elasticsearch.
I read a lot articles about using Elasticsearch [with spring without spring-data-elasticsearch](https://github.com/dadoonet/spring-elasticsearch/), [with spring-data-elasticsearch](https://github.com/spring-projects/spring-data-elasticsearch) and now I see [this legacy-search project](https://github.com/dadoonet/legacy-search).

What is the purpose of this project while you can use spring-data-elasticsearch for example?

Thank you

**Comment by dadoonet** [comment]
Hi

> I'm really confused what is the best way of using the Elasticsearch in a spring boot project?

Spring boot is not Spring data. So it depends if you want to use Spring Data or not.
This project is a demo project to show how easy it is to communicate with elasticsearch in Java. 

It was originally using RestX instead of Spring Boot. It could use any other framework and is not really tight to a given technology but Elasticsearch.

If you are using Spring Data and want to implement faster your project, probably using spring data elasticsearch will help you.
If you want to have more control on what is happening, you could use the techniques I'm sharing here and implement exactly what you need. And (but I'm probably biased), I prefer doing things with elasticsearch by myself.

About Spring Data Elasticsearch, I think that the team did a very great job with the version 4.0 by switching to the REST Client and adding compatibility with Elasticsearch 7.x.

> What is the purpose of this project while you can use spring-data-elasticsearch for example?

It's a demo project to show case how to use the High Level Rest Client.
I'm using it while doing 100% live coding sessions like [this one for GeekOut EE](https://player.vimeo.com/video/274560967) in June 2018. A more recent video will be released at the end of May.

I hope I addressed your questions. Feel free to ask more by commenting this issue.

**Comment by BigGitWorld** [comment]
Hello.
Your video was great and answered many of my questions. 
I thought the best and simplest way to use the Elasticsearch in java is to depend on Spring Data, but your video changed my mind.
Thank you very much.
